# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# 기본 언어 : 영어
en:
  languageCode: en-us
  contentDir: content/en

# 한국어 지원 세팅
ko:
 languageCode: ko
 contentDir: content/ko
 title: DongYoung Kim
 params:
   description: 김동영
 menu:
   main:
    - name: 홈
      url: '#about'
      weight: 10
    - name: 프로젝트
      url: '#projects'
      weight: 20
    - name: 출판
      url: '#featured'
      weight: 30
    - name: 포스트
      url: '#posts'
      weight: 40
    - name : 태그
      url: '/tags'
      weight : 50
    - name: 이력서
      url: https://drive.google.com/file/d/1nk7aYiYmrUq6o-cf4qsn0cV9KE-28tqU/view
      weight: 70