# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ko:
 languageCode: ko
 contentDir: content/ko
 title: DongYoung Kim
 params:
   description: 한국어 세팅
 menu:
   main:
     - name: 대하여...
       url: '#about'
       weight: 1
